module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module'
  },
  env: {
    'browser': true
  },
  plugins: [
    'ember-extra-linting'
  ],
  rules: {
    'ember-extra-linting/no-ember-autogenerated-comments': 2,
    'ember-extra-linting/ember-no-double-sets': 2
  }
};