module.exports = {
  root: true,
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module'
  },
  env: {
    'browser': true
  },
  plugins: [
    'ember-extra-linting'
  ],
  rules: {
    'ember-extra-linting/ember-no-autogenerated-comments': 2,
    'ember-extra-linting/ember-no-double-gets': 2,
    'ember-extra-linting/ember-no-double-sets': 2,
    'ember-extra-linting/ember-require-inject-as-service': 2,
    'ember-extra-linting/ember-require-service-used': 2,
    'ember-extra-linting/ember-no-pointless-service-arguments': 2
  }
};